aFile = readLines(classification)
library(tm)
colnames(final)<-c("no","title","class_label","url")
colnames(unskewed_data)
View(unskewed_data)
myCorpus = Corpus(VectorSource(tolower(unskewed_data$title)))
#class(myCorpus)
myCorpus=tm_map(myCorpus,stripWhitespace)
myCorpus = tm_map(myCorpus, content_transformer(tolower))
myCorpus = tm_map(myCorpus, removePunctuation)
myCorpus = tm_map(myCorpus, removeNumbers)
myCorpus = tm_map(myCorpus, removeWords,stopwords("english"))
myCorpus=tm_map(myCorpus,stripWhitespace)
myCorpus <- tm_map(myCorpus, PlainTextDocument)
myDTM=DocumentTermMatrix(myCorpus)
library(slam)
colTotals <-  col_sums(myDTM)
dtm2 <- myDTM[,which(colTotals >0)]
dim(dtm2)